config/routes.rb
Myhome::Application.routes.draw do
  root 'home#welcome'

  namespace :comptes do
    get "/" => "transactions#index"

    concern :with_transactions do |options|
      resources :transactions, options do
        collection do
          get "ajouter"
        end
      end
    end

    concerns :with_transactions
    resources :transaction_monnaies, controller: "transactions"
    resources :transaction_cartes, controller: "transactions"
    resources :transfers, controller: "transactions"

    resources :comptes, concerns: [ :with_transactions ] do
      member do
        get :solde
        post :solde
        get :summary
        get :statistics
        post :statistics
        get :validate
        post :validate
      end
    end

    resources :categories
  end

  namespace :date_marker do
    resources :events do
      member do
        get :get_day
        post :get_day
      end
    end
  end

end

app/models/comptes.rb
module Comptes
  def self.table_name_prefix
    'comptes_'
  end
end

app/models/comptes/categorization.rb
class Comptes::Categorization < ActiveRecord::Base
  belongs_to :transaction
  belongs_to :category

  validates :transaction, presence: true
  validates :category, presence: true
end

app/models/comptes/category.rb
class Comptes::Category < ActiveRecord::Base
  has_many :categorizations, dependent: :destroy
  accepts_nested_attributes_for :categorizations
  has_many :transactions, through: :categorizations

  validates :nom, presence: true, uniqueness: true
end

app/models/comptes/compte.rb
module Comptes

  class Compte < ActiveRecord::Base
    has_many :transactions
    attr_readonly :solde_historique

    validates :nom, presence: true, uniqueness: true
    validates :solde_historique, presence: true, numericality: { only_integer: true }

    def solde_formatte with_currency = true
      ComptesHelper::format_amount solde, with_currency
    end

    # Get the solde of the account
    # Params
    # options: options to use
    #   - :until use .until to compute the solde (default: no limit)
    #   - :before use .before on transaction (default: no limit)
    #   - :with_currency format the solde with the currency (default: false)
    # Returns the decoded solde
    def solde options = {}
      all_transactions = transactions
      # Ne pas compter les paiements en monnaie
      tansactions_monnaie = transactions.where(type: TransactionMonnaie)

      raise ArgumentError, "You are using both :before and :until" if options.key?(:before) && options.key?(:until)
      if options.key?(:until)
        all_transactions = all_transactions.until options[:until]
        tansactions_monnaie = tansactions_monnaie.until options[:until]
      end
      if options.key?(:before)
        all_transactions = all_transactions.before options[:before]
        tansactions_monnaie = tansactions_monnaie.before options[:before]
      end

      solde = solde_historique + all_transactions.sum(:somme) - tansactions_monnaie.sum(:somme)
      return solde if options[:raw]

      solde = ComptesHelper.decode_amount solde
      options[:with_currency] ? ComptesHelper::format_amount(solde) : solde
    end

    def validate date = nil
      validated_solde = date ? solde(until: date) : solde
      now = Time.now
      date ||= now
      update! validation_date: now, validated_date: date, validation_solde: ComptesHelper.encode_amount(validated_solde)
    end

    def unvalidated_transactions
      if validation_date
        transactions.where("created_at >= :validation_date OR updated_at >= :validation_date", validation_date: validation_date)
      else
        transactions
      end
    end
  end

end

app/models/comptes/transaction_carte.rb
module Comptes

  class TransactionCarte < Transaction
    def self.type_name
      "Carte"
    end
  end

end

app/controllers/comptes/categories_controller.rb
class Comptes::CategoriesController < ApplicationController
  before_action :set_comptes_category, only: [:show, :edit, :update, :destroy]

  # GET /comptes/categories
  # GET /comptes/categories.json
  def index
    @comptes_categories = Comptes::Category.order(nom: :asc)
  end

  # GET /comptes/categories/1
  # GET /comptes/categories/1.json
  def show
  end

  # GET /comptes/categories/new
  def new
    @comptes_category = Comptes::Category.new
  end

  # GET /comptes/categories/1/edit
  def edit
  end

  # POST /comptes/categories
  # POST /comptes/categories.json
  def create
    @comptes_category = Comptes::Category.new(comptes_category_params)

    respond_to do |format|
      if @comptes_category.save
        format.html { redirect_to @comptes_category, notice: 'Category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @comptes_category }
      else
        format.html { render action: 'new' }
        format.json { render json: @comptes_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comptes/categories/1
  # PATCH/PUT /comptes/categories/1.json
  def update
    respond_to do |format|
      if @comptes_category.update(comptes_category_params)
        format.html { redirect_to @comptes_category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comptes_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comptes/categories/1
  # DELETE /comptes/categories/1.json
  def destroy
    @comptes_category.destroy
    respond_to do |format|
      format.html { redirect_to comptes_categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comptes_category
      @comptes_category = Comptes::Category.find_by_id(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comptes_category_params
      params.require(:comptes_category).permit(:nom)
    end
end

app/controllers/comptes/comptes_controller.rb
module Comptes

  class ComptesController < ApplicationController
    before_action :get_compte, [:show, :edit, :udpate, :solde, :summary, :statistics, :validate]

    def index
      @comptes = Compte.all
    end

    def new
      @compte = Compte.new()
    end

    def create
      parameters = format_params(comptes_params)
      @compte = Compte.new parameters

      if @compte.save
        redirect_to @compte
      else
        render 'new'
      end
    end

    def show
      @transactions = @compte.transactions.order(jour: :desc, created_at: :desc).limit(5) if @compte
    end

    def edit
    end

    def update
      unless @compte
        respond_to do |format|
          format.html { render :update }
          format.json { render json: { errors: "Le compte #{params[:id]} n'existe pas." } }
        end
      end

      parameters = format_params comptes_params
      # Pour l'instant, on ne touche pas au solde
      parameters.delete :solde_historique

      if @compte.update parameters
        respond_to do |format|
          format.html { render :show }
          format.json { render json: @compte }
        end
      else
        respond_to do |format|
          format.html { render :edit }
          format.json { render json: { errors: @compte.errors } }
        end
      end
    end

    def solde
      if request.post?
        if @compte && ApplicationHelper::is_a_date?(params[:date])
          @date = Date.parse params[:date]
          @solde = ComptesHelper.format_amount @compte.solde(until: @date), true
        end
      end
    end

    def summary
      return unless @compte

      now = Date.today
      current_month = Date.new now.year, now.month

      @previous_months = []
      12.times do |i|
        month_beginning = current_month << i
        next_month = month_beginning >> 1

        solde = @compte.solde(before: next_month, with_currency: false)
        debit = get_changing_trades(@compte.transactions.expenses, month_beginning, next_month).abs
        credit = get_changing_trades(@compte.transactions.revenues, month_beginning, next_month)

        month_data = {
          date: month_beginning,
          solde: solde,
          debit: ComptesHelper.decode_amount(-debit),
          credit: ComptesHelper.decode_amount(credit),
          expense: ComptesHelper.decode_amount(credit - debit)
        }
        @previous_months << month_data
      end
    end

    def statistics
      if request.post?
        date_format = "%Y-%m"
        if @compte && ApplicationHelper::is_a_date?(params[:month], date_format)
          @statistics = { credit: {}, debit: {} }

          month = Date.strptime params[:month], date_format
          next_month = month >> 1

          Category.find_each do |category|
            transactions = category.transactions.of_account(@compte).since(month).before(next_month)

            debit = transactions.expenses.sum(:somme).abs
            credit = transactions.revenues.sum(:somme)

            @statistics[:credit][category.nom] = ComptesHelper::decode_amount(credit) if credit > 0
            @statistics[:debit][category.nom] = ComptesHelper::decode_amount(debit) if debit > 0
          end
        else
          @statistics = {}
        end

        respond_to do |format|
          format.json { render json: @statistics }
        end
      end
    end

    def validate
      if request.post?
        if @compte
          @date = ApplicationHelper::is_a_date?(params[:date]) ? Date.parse(params[:date]) : nil
          if @compte.validate @date
            respond_to do |format|
              format.html { redirect_to @compte }
              format.js {}
            end
          else
            respond_to do |format|
              format.html { render }
              format.js {}
            end
          end
        else
          raise ActiveRecord::RecordNotFound
        end
      else
        if @compte
          @unvalidated_transactions = @compte.unvalidated_transactions.paginate(page: params[:page], per_page: 20).order(jour: :desc, updated_at: :desc)
        end
      end
    end

    private
      def comptes_params
        params.require(:comptes_compte).permit(:nom, :solde_historique)
      end

      def format_params parameters
        solde_historique = parameters[:solde_historique]
        parameters[:solde_historique] = ComptesHelper.encode_amount solde_historique if ApplicationHelper.is_a_number? solde_historique

        parameters
      end

      def get_compte
        @compte = Compte.find_by_id params[:id]
      end

      # Get the trades that affect the solde of the account
      # Params
      #   account account to consider
      #   from initial datetime (included)
      #   to ending datetime ()
      # Returns the appropriate transactions
      def get_changing_trades transactions, from, to, &conditions
        all_trades = transactions.since(from).before(to)
        total = all_trades.sum(:somme)
        total_monnaie = all_trades.where(type: TransactionMonnaie).sum(:somme)

        total - total_monnaie
      end
  end

end # module Comptes

app/controllers/comptes/transactions_controller.rb
require "enum_class"

module Comptes

  class TransactionsController < ApplicationController
    Types = EnumClass.create_series [:default, :monnaie, :carte, :virement]
    class << Types
      class Error < RangeError
      end

      def get_class type
        case type
        when Types.MONNAIE
          Comptes::TransactionMonnaie
        when Types.CARTE
          Comptes::TransactionCarte
        when Types.VIREMENT
          Comptes::Transfer
        when Types.DEFAULT
          Comptes::Transaction
        else
          raise Error, "Unknown type #{type}"
        end
      end

      def from_class transaction
        case transaction
        when Comptes::TransactionCarte
          Types.CARTE
        when Comptes::TransactionMonnaie
          Types.MONNAIE
        when Comptes::Transfer
          Types.VIREMENT
        when Comptes::Transaction
          Types.DEFAULT
        else
          raise Error, "Unknown class #{transaction}"
        end
      end
    end

    before_action :get_transaction, only: [:show, :edit, :update]
    before_action :get_context, only: [:index, :summary, :ajouter]
    before_action :get_allowed_resources, only: [:ajouter, :edit, :update]
    before_action :get_formatted_parameters, only: [:create, :update]

    def index
      @transactions = Transaction.all
      @transactions.where!(compte_id: @compte.id) if @compte
      respond_to do |format|
        format.html do
          @transactions = @transactions.paginate(page: params[:page], per_page: 20).order(jour: :desc, updated_at: :desc)
          render
        end
        format.csv { send_data @transactions.to_csv }
        format.xls
      end
    end

    def ajouter
      @transaction = Transaction.new
      @transaction.compte = @compte if @compte
    end

    # def new
    # end

    def create
      if @transaction_type
        transaction_class = Types.get_class @transaction_type
        @transaction = transaction_class.new @parameters
      else
        @transaction = Comptes::Transaction.new
        @transaction.errors.add :type, "Type de transaction inconnu"
      end

      if @transaction.errors.empty? && @transaction.save
        # set the categories (workaround)
        @transaction.categories = @categories
        flash[:error] = "Erreur dans l'assignation des catégories." unless @transaction.save

        respond_to do |format|
          format.html { redirect_to @transaction }
          format.json do
            render json: { transaction: {
              id: @transaction.id,
              titre: @transaction.titre,
              somme: @transaction.somme_formattee,
              compte: @transaction.compte.nom,
              jour: @transaction.jour_formatte,
              type: @transaction.class.type_name,
              categories: @transaction.categories.collect{ |categorie| categorie.nom }.join(', ')
            }}
          end
          format.js {}
        end
      else
        respond_to do |format|
          format.html { render "new" }
          format.json { render json: { errors: @transaction.errors.messages } }
          format.js {}
        end
      end
    end

    def edit
    end

    def show
    end

    def update
      if @transaction
        @transaction.categories = @categories
      end

      if @transaction && @transaction.update(@parameters)
        respond_to do |format|
          format.html { render :show }
        end
      else
        respond_to do |format|
          format.html { render :edit }
        end
      end
    end

    def destroy
      @transaction = Comptes::Transaction.find_by_id(params[:id])
      @success = false
      if @transaction
        if @transaction.destroy
          flash[:notice] = "Transaction supprimée avec succés"
          @success = true
        else
          flash[:error] = "Impossible de supprimer la transaction"
        end
      else
        flash[:error] = "Transaction invalide. Aucune suppression."
      end

      respond_to do |format|
        format.html { redirect_to comptes_transactions_path }
        format.js {}
      end
    end

    private
      def get_transaction
        @transaction = Transaction.find_by_id params[:id]
      end

      def get_context
        @compte = Compte.find_by_id params[:compte_id]
      end

      def transaction_params
        params.require(:comptes_transaction).permit(:titre, :somme, :jour, :compte_id, :type, :negative, { categories: [] })
      end

      # Formate les parametres de la transaction
      # * convertit la somme en centimes
      def format_params parameters
        somme = parameters[:somme]
        negative_sign = parameters.delete(:negative).to_i || 0
        if ApplicationHelper::is_a_number? somme
          parameters[:somme] = ComptesHelper.encode_amount(somme) * (negative_sign == 1 ? -1 : 1)
        end

        transaction_type = get_transaction_type(parameters.delete(:type))
        categories = get_categories(parameters.delete(:categories))

        return parameters, transaction_type, categories
      end

      def get_formatted_parameters
        @parameters, @transaction_type, @categories = format_params(transaction_params)
      end

      def get_categories category_ids
        category_ids ||= []

        category_ids.collect{ |id| Category.find_by_id id }.delete_if(&:nil?)
      end

      def get_transaction_type type
        transaction_type = type ? type.to_i : nil
        Types.is_valid?(transaction_type) ? Types.value_of(transaction_type) : nil
      end

      def get_allowed_resources
        @categories = Category.order(nom: :asc)
        @comptes = Compte.order(nom: :asc)
        @types = Comptes::TransactionsController::Types
      end
  end

end

app/helpers/comptes/categories_helper.rb
module Comptes::CategoriesHelper
end

app/helpers/comptes/comptes_helper.rb
module Comptes::ComptesHelper

  # Formats a value in cents into a decimal value with 2 decimals and a final €
  def self.format_amount value, with_currency = true
    (with_currency ? "%.2f €" : "%.2f") % [ value.to_f ]
  end

  # Convertit une somme pour un stockage sous forme d'entier en centimes
  # Params:
  #   value: la somme
  # Returns:
  #   la valeur entière correspondante
  def self.encode_amount value
    (value.to_f * 100).round.to_i
  end

  # Convertit une somme stockéé en entier sous sa forme originale
  # Params:
  #   value: la somme stockée
  # Returns:
  #   la valeur correspondante
  def self.decode_amount value
    (value.to_f / 100)
  end
end

app/helpers/comptes/transactions_helper.rb
module Comptes::TransactionsHelper
end

app/views/comptes/transactions/_form.html.erb
<%= form_for @transaction.becomes(Comptes::Transaction), remote: remote, html: { id: "transaction-form", class: "form-horizontal", role: "form" } do |form| %>
  <%= render "shared/form_errors", model: @transaction %>

  <div class="form-group">
    <%= form.label :titre, class: "col-md-3 control-label" %>
    <div class="col-md-9">
      <%= form.text_field :titre, class: "form-control", placeholder: "Titre de la transaction", required: "" %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :somme, class: "col-md-3 control-label" %>
    <div class="col-md-9">
      <div class="input-group">
        <% somme = if @transaction.somme
              Comptes::ComptesHelper::decode_amount @transaction.somme
            elsif params[:comptes_transaction] && params[:comptes_transaction][:somme]
              params[:comptes_transaction][:somme]
            else
              0
            end
        %>
        <span class="input-group-addon" id="sign-box">
          <%= form.check_box :negative, checked: (somme <= 0) %>
          <%= form.label :negative, (somme <= 0 ? "-" : '+') %>
        </span>
        <%= form.number_field :somme, value: somme.abs, class: "form-control", min: 0, step: 0.01, placeholder: "Montant de la transaction", required: "" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :compte_id, "Compte", class: "col-md-3 control-label" %>
    <%
    compte_options = {}
    compte_options[:selected] = @transaction.compte.id if @transaction.compte
    %>
    <div class="col-md-9">
      <%= form.collection_select(:compte_id, @comptes, :id, :nom, compte_options, class: "form-control", required: "") %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :jour, "Date", class: "col-md-3 control-label" %>
    <div class="col-md-9">
      <%= form.date_field :jour, value: Date.today,  placeholder: "jj/mm/aaaa", required: "" %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :type, "Type de transaction", class: "col-md-3 control-label" %>
    <div class="col-md-9">
      <%
      type_options = {}
      type_options[:selected] = Comptes::TransactionsController::Types.from_class(@transaction).value if @transaction.class.type_name
      %>
      <%= form.collection_select(:type, @types, :value, :name, type_options, class: "form-control", required: "", readonly: !@transaction.new_record?) %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :categories, "Catégories", class: "col-md-3 control-label" %>
    <div class="col-md-9">
      <%
      categories_options = {}
      categories_options[:selected] = @transaction.categories.collect { |categorie| categorie.id }
      %>
      <%= form.collection_select(:categories, @categories, :id, :nom, categories_options, class: "form-control", multiple: true, size: 10) %>
    </div>
  </div>

  <div class="col-md-offset-3 col-md-9">
    <%= form.submit "#{@transaction.new_record? ? "Ajouter" : "Éditer"} l'opération", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/comptes/transactions/_section_menu.html.erb
<li>
	<span class="section-title"><%= HtmlHelper::Bootstrap::glyphicon('tasks') %> Transactions</span>
	<ul>
	  <li><%= link_to "Liste", comptes_transactions_path %></li>
	  <li><%= link_to "Ajouter", ajouter_comptes_transactions_path %></li>
	</ul>
</li>

<% if @compte %>
<li>
	<span class="section-title"><%= HtmlHelper::Bootstrap::glyphicon('tasks') %> [ <%= @compte.nom %> ]</span>
	<ul>
	  <li><%= link_to "Détails", comptes_compte_path(@compte) %></li>
	  <li><%= link_to "Solde interactif", solde_comptes_compte_path(@compte) %></li>
	  <li><%= link_to "Transactions", comptes_compte_transactions_path(@compte) %></li>
	</ul>
</li>
<% end %>

app/views/comptes/transactions/_transaction.html.erb
    <tr class="transaction" id="transaction-<%= transaction.id %>">
      <td><%= transaction.jour %></td>
      <td><%= transaction.titre %></td>
      <td>
        <%= HtmlHelper::Bootstrap::value_badge transaction.somme, transaction.somme_formattee %>
      </td>
      <td><%= transaction.compte.nom %></td>
      <td><%= transaction.class.type_name %></td>
      <td>
        <%= link_to raw('<i class="glyphicon glyphicon-eye-open"></i>'), transaction, class: "btn btn-info" %>
        <%= link_away raw('<i class="glyphicon glyphicon-pencil"></i>'), edit_comptes_transaction_path(transaction), class: "btn btn-info" %>
        <%= link_to raw('<i class="glyphicon glyphicon-trash"></i>'), transaction, method: :delete, remote: true, data: { confirm: "Sûr de vouloir supprimer la transaction ?" }, class: "btn btn-danger" %>
      </td>
    </tr>

app/views/comptes/transactions/_transactions.html.erb
<% allow_empty ||= false %>

<% if transactions && (allow_empty || !transactions.empty?) %>

<table id="transactions-table" class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Date</th>
      <th>Libellé</th>
      <th>Montant</th>
      <th>Compte</th>
      <th>Paiement</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <%= render transactions %>
  </tbody>
</table>

<% else %>
<p>Aucune transaction pour le moment</p>
<% end %>

app/views/comptes/transactions/ajouter.html.erb
<% provide :title, "Ajouter de nouvelles transactions" %>

<%=
  render partial: 'form', locals: { remote: true }
%>

<h2>Opérations enregistrées</h2>

<%= render partial: 'transactions', object: [], locals: { allow_empty: true } %>

app/views/comptes/transactions/create.js.erb
$("#transaction-errors").empty();

<% unless @transaction.errors.any? %>

  $("<%= escape_javascript render @transaction %>").prependTo("#transactions-table tbody");

  var transaction_form = $("#transaction-form");
  transaction_form.find("input[name*='titre']").val('').focus()
  transaction_form.find("input[name*='somme']").val('')

<% else %>

  $('form').prepend("<%= escape_javascript render 'shared/form_errors', model: @transaction, wrapper_id: 'transaction-errors' %>");

<% end %>

app/views/comptes/transactions/destroy.js.erb
<% if @success %>

	$('#transaction-<%= @transaction.id %>').remove();

<% else %>

	console.log('Failed to delete transaction <%= @transaction.titre %> (<%= @transaction.id %>)');

<% end %>

app/views/comptes/transactions/edit.html.erb
<% if @transaction %>

<h1>Édition de la transaction</h1>

<%=
  render partial: 'form', locals: {remote: false}
%>

<p>
  <%= link_to "Retour", @transaction %>
</p>

<% else %>

<p class="alert alert-danger">
  La transaction <%= params[:id] %> n'existe pas.
</p>

<% end %>

app/views/comptes/transactions/index.html.erb
<% provide :title, "Sous sous qui rentrent et qui sortent" %>

<%= will_paginate @transactions %>

<%= render partial: 'transactions', object: @transactions %>

<%= will_paginate @transactions %>

app/views/comptes/transactions/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Transactions">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Titre</Data></Cell>
        <Cell><Data ss:Type="String">Montant</Data></Cell>
        <Cell><Data ss:Type="String">Date</Data></Cell>
        <Cell><Data ss:Type="String">Compte</Data></Cell>
        <Cell><Data ss:Type="String">Categorie</Data></Cell>
      </Row>
    <% @transactions.each do |transaction| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= transaction.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= transaction.titre %></Data></Cell>
        <Cell><Data ss:Type="String"><%= transaction.somme %></Data></Cell>
        <Cell><Data ss:Type="String"><%= transaction.jour_formatte %></Data></Cell>
        <Cell><Data ss:Type="String"><%= transaction.compte.nom %></Data></Cell>
        <Cell><Data ss:Type="String"><%= transaction.categories.empty? ? '' : transaction.categories.first.nom %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/comptes/transactions/show.html.erb
<% if @transaction %>

<h1><%= @transaction.titre %></h1>

<p class="lead">
  Montant : <span class="label label-info"><%= @transaction.somme_formattee %></span>
</p>

<p>
  Date : <%= @transaction.jour_formatte %><br/>
  Type de paiement : <%= @transaction.class.type_name %><br/>
  Compte : <%= @transaction.compte.nom %>
</p>

<p>
  Catégories: <%= @transaction.categories.any? ? @transaction.categories.collect{ |categorie| categorie.nom }.join(', ') : "aucune" %>
</p>

<p>
  <%= link_to "Éditer", edit_comptes_transaction_path(@transaction) %>
</p>

<% else %>

<p class="alert alert-danger">
  La transaction <%= params[:id] %> n'existe pas.
</p>

<% end %>