config/routes.rb
Myhome::Application.routes.draw do
  root 'home#welcome'

  namespace :comptes do
    get "/" => "transactions#index"

    concern :with_transactions do |options|
      resources :transactions, options do
        collection do
          get "ajouter"
        end
      end
    end

    concerns :with_transactions
    resources :transaction_monnaies, controller: "transactions"
    resources :transaction_cartes, controller: "transactions"
    resources :transfers, controller: "transactions"

    resources :comptes, concerns: [ :with_transactions ] do
      member do
        get :solde
        post :solde
        get :summary
        get :statistics
        post :statistics
        get :validate
        post :validate
      end
    end

    resources :categories
  end

  namespace :date_marker do
    resources :events do
      member do
        get :get_day
        post :get_day
      end
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def welcome
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_section_menu.html.erb
<!-- Nothing to do -->

app/views/home/welcome.html.erb
<h1>Home#welcome</h1>

<h2>Gestion des comptes</h2>
<p>
  <%= link_to "Accès aux comptes", comptes_path %><br/>
  <%= link_to 'Création de comptes', new_comptes_compte_path %>
</p>

<h2>Gestion des transactions</h2>
<p>
  <%= link_to "Liste des dernières transactions", comptes_transactions_path %><br/>
  <%= link_to "Enregistrer de nouvelles transactions", ajouter_comptes_transactions_path %>
</p>

<h2>Gestion des catégories</h2>
<p>
  <%= link_to "Liste des catégories", comptes_categories_path %><br/>
  <%= link_to "Enregistrer de nouvelles catégories", new_comptes_category_path %>
</p>

<h2>Date markers</h2>
<p>
  <%= link_to "Espace de marqueurs de dates", date_marker_events_path %>
</p>