config/routes.rb
Myhome::Application.routes.draw do
  root 'home#welcome'

  namespace :comptes do
    get "/" => "transactions#index"

    concern :with_transactions do |options|
      resources :transactions, options do
        collection do
          get "ajouter"
        end
      end
    end

    concerns :with_transactions
    resources :transaction_monnaies, controller: "transactions"
    resources :transaction_cartes, controller: "transactions"
    resources :transfers, controller: "transactions"

    resources :comptes, concerns: [ :with_transactions ] do
      member do
        get :solde
        post :solde
        get :summary
        get :statistics
        post :statistics
        get :validate
        post :validate
      end
    end

    resources :categories
  end

  namespace :date_marker do
    resources :events do
      member do
        get :get_day
        post :get_day
      end
    end
  end

end

app/models/comptes.rb
module Comptes
  def self.table_name_prefix
    'comptes_'
  end
end

app/models/comptes/categorization.rb
class Comptes::Categorization < ActiveRecord::Base
  belongs_to :transaction
  belongs_to :category

  validates :transaction, presence: true
  validates :category, presence: true
end

app/models/comptes/category.rb
class Comptes::Category < ActiveRecord::Base
  has_many :categorizations, dependent: :destroy
  accepts_nested_attributes_for :categorizations
  has_many :transactions, through: :categorizations

  validates :nom, presence: true, uniqueness: true
end

app/models/comptes/compte.rb
module Comptes

  class Compte < ActiveRecord::Base
    has_many :transactions
    attr_readonly :solde_historique

    validates :nom, presence: true, uniqueness: true
    validates :solde_historique, presence: true, numericality: { only_integer: true }

    def solde_formatte with_currency = true
      ComptesHelper::format_amount solde, with_currency
    end

    # Get the solde of the account
    # Params
    # options: options to use
    #   - :until use .until to compute the solde (default: no limit)
    #   - :before use .before on transaction (default: no limit)
    #   - :with_currency format the solde with the currency (default: false)
    # Returns the decoded solde
    def solde options = {}
      all_transactions = transactions
      # Ne pas compter les paiements en monnaie
      tansactions_monnaie = transactions.where(type: TransactionMonnaie)

      raise ArgumentError, "You are using both :before and :until" if options.key?(:before) && options.key?(:until)
      if options.key?(:until)
        all_transactions = all_transactions.until options[:until]
        tansactions_monnaie = tansactions_monnaie.until options[:until]
      end
      if options.key?(:before)
        all_transactions = all_transactions.before options[:before]
        tansactions_monnaie = tansactions_monnaie.before options[:before]
      end

      solde = solde_historique + all_transactions.sum(:somme) - tansactions_monnaie.sum(:somme)
      return solde if options[:raw]

      solde = ComptesHelper.decode_amount solde
      options[:with_currency] ? ComptesHelper::format_amount(solde) : solde
    end

    def validate date = nil
      validated_solde = date ? solde(until: date) : solde
      now = Time.now
      date ||= now
      update! validation_date: now, validated_date: date, validation_solde: ComptesHelper.encode_amount(validated_solde)
    end

    def unvalidated_transactions
      if validation_date
        transactions.where("created_at >= :validation_date OR updated_at >= :validation_date", validation_date: validation_date)
      else
        transactions
      end
    end
  end

end

app/models/comptes/transaction_carte.rb
module Comptes

  class TransactionCarte < Transaction
    def self.type_name
      "Carte"
    end
  end

end

app/controllers/comptes/categories_controller.rb
class Comptes::CategoriesController < ApplicationController
  before_action :set_comptes_category, only: [:show, :edit, :update, :destroy]

  # GET /comptes/categories
  # GET /comptes/categories.json
  def index
    @comptes_categories = Comptes::Category.order(nom: :asc)
  end

  # GET /comptes/categories/1
  # GET /comptes/categories/1.json
  def show
  end

  # GET /comptes/categories/new
  def new
    @comptes_category = Comptes::Category.new
  end

  # GET /comptes/categories/1/edit
  def edit
  end

  # POST /comptes/categories
  # POST /comptes/categories.json
  def create
    @comptes_category = Comptes::Category.new(comptes_category_params)

    respond_to do |format|
      if @comptes_category.save
        format.html { redirect_to @comptes_category, notice: 'Category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @comptes_category }
      else
        format.html { render action: 'new' }
        format.json { render json: @comptes_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comptes/categories/1
  # PATCH/PUT /comptes/categories/1.json
  def update
    respond_to do |format|
      if @comptes_category.update(comptes_category_params)
        format.html { redirect_to @comptes_category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comptes_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comptes/categories/1
  # DELETE /comptes/categories/1.json
  def destroy
    @comptes_category.destroy
    respond_to do |format|
      format.html { redirect_to comptes_categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comptes_category
      @comptes_category = Comptes::Category.find_by_id(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comptes_category_params
      params.require(:comptes_category).permit(:nom)
    end
end

app/controllers/comptes/comptes_controller.rb
module Comptes

  class ComptesController < ApplicationController
    before_action :get_compte, [:show, :edit, :udpate, :solde, :summary, :statistics, :validate]

    def index
      @comptes = Compte.all
    end

    def new
      @compte = Compte.new()
    end

    def create
      parameters = format_params(comptes_params)
      @compte = Compte.new parameters

      if @compte.save
        redirect_to @compte
      else
        render 'new'
      end
    end

    def show
      @transactions = @compte.transactions.order(jour: :desc, created_at: :desc).limit(5) if @compte
    end

    def edit
    end

    def update
      unless @compte
        respond_to do |format|
          format.html { render :update }
          format.json { render json: { errors: "Le compte #{params[:id]} n'existe pas." } }
        end
      end

      parameters = format_params comptes_params
      # Pour l'instant, on ne touche pas au solde
      parameters.delete :solde_historique

      if @compte.update parameters
        respond_to do |format|
          format.html { render :show }
          format.json { render json: @compte }
        end
      else
        respond_to do |format|
          format.html { render :edit }
          format.json { render json: { errors: @compte.errors } }
        end
      end
    end

    def solde
      if request.post?
        if @compte && ApplicationHelper::is_a_date?(params[:date])
          @date = Date.parse params[:date]
          @solde = ComptesHelper.format_amount @compte.solde(until: @date), true
        end
      end
    end

    def summary
      return unless @compte

      now = Date.today
      current_month = Date.new now.year, now.month

      @previous_months = []
      12.times do |i|
        month_beginning = current_month << i
        next_month = month_beginning >> 1

        solde = @compte.solde(before: next_month, with_currency: false)
        debit = get_changing_trades(@compte.transactions.expenses, month_beginning, next_month).abs
        credit = get_changing_trades(@compte.transactions.revenues, month_beginning, next_month)

        month_data = {
          date: month_beginning,
          solde: solde,
          debit: ComptesHelper.decode_amount(-debit),
          credit: ComptesHelper.decode_amount(credit),
          expense: ComptesHelper.decode_amount(credit - debit)
        }
        @previous_months << month_data
      end
    end

    def statistics
      if request.post?
        date_format = "%Y-%m"
        if @compte && ApplicationHelper::is_a_date?(params[:month], date_format)
          @statistics = { credit: {}, debit: {} }

          month = Date.strptime params[:month], date_format
          next_month = month >> 1

          Category.find_each do |category|
            transactions = category.transactions.of_account(@compte).since(month).before(next_month)

            debit = transactions.expenses.sum(:somme).abs
            credit = transactions.revenues.sum(:somme)

            @statistics[:credit][category.nom] = ComptesHelper::decode_amount(credit) if credit > 0
            @statistics[:debit][category.nom] = ComptesHelper::decode_amount(debit) if debit > 0
          end
        else
          @statistics = {}
        end

        respond_to do |format|
          format.json { render json: @statistics }
        end
      end
    end

    def validate
      if request.post?
        if @compte
          @date = ApplicationHelper::is_a_date?(params[:date]) ? Date.parse(params[:date]) : nil
          if @compte.validate @date
            respond_to do |format|
              format.html { redirect_to @compte }
              format.js {}
            end
          else
            respond_to do |format|
              format.html { render }
              format.js {}
            end
          end
        else
          raise ActiveRecord::RecordNotFound
        end
      else
        if @compte
          @unvalidated_transactions = @compte.unvalidated_transactions.paginate(page: params[:page], per_page: 20).order(jour: :desc, updated_at: :desc)
        end
      end
    end

    private
      def comptes_params
        params.require(:comptes_compte).permit(:nom, :solde_historique)
      end

      def format_params parameters
        solde_historique = parameters[:solde_historique]
        parameters[:solde_historique] = ComptesHelper.encode_amount solde_historique if ApplicationHelper.is_a_number? solde_historique

        parameters
      end

      def get_compte
        @compte = Compte.find_by_id params[:id]
      end

      # Get the trades that affect the solde of the account
      # Params
      #   account account to consider
      #   from initial datetime (included)
      #   to ending datetime ()
      # Returns the appropriate transactions
      def get_changing_trades transactions, from, to, &conditions
        all_trades = transactions.since(from).before(to)
        total = all_trades.sum(:somme)
        total_monnaie = all_trades.where(type: TransactionMonnaie).sum(:somme)

        total - total_monnaie
      end
  end

end # module Comptes

app/controllers/comptes/transactions_controller.rb
require "enum_class"

module Comptes

  class TransactionsController < ApplicationController
    Types = EnumClass.create_series [:default, :monnaie, :carte, :virement]
    class << Types
      class Error < RangeError
      end

      def get_class type
        case type
        when Types.MONNAIE
          Comptes::TransactionMonnaie
        when Types.CARTE
          Comptes::TransactionCarte
        when Types.VIREMENT
          Comptes::Transfer
        when Types.DEFAULT
          Comptes::Transaction
        else
          raise Error, "Unknown type #{type}"
        end
      end

      def from_class transaction
        case transaction
        when Comptes::TransactionCarte
          Types.CARTE
        when Comptes::TransactionMonnaie
          Types.MONNAIE
        when Comptes::Transfer
          Types.VIREMENT
        when Comptes::Transaction
          Types.DEFAULT
        else
          raise Error, "Unknown class #{transaction}"
        end
      end
    end

    before_action :get_transaction, only: [:show, :edit, :update]
    before_action :get_context, only: [:index, :summary, :ajouter]
    before_action :get_allowed_resources, only: [:ajouter, :edit, :update]
    before_action :get_formatted_parameters, only: [:create, :update]

    def index
      @transactions = Transaction.all
      @transactions.where!(compte_id: @compte.id) if @compte
      respond_to do |format|
        format.html do
          @transactions = @transactions.paginate(page: params[:page], per_page: 20).order(jour: :desc, updated_at: :desc)
          render
        end
        format.csv { send_data @transactions.to_csv }
        format.xls
      end
    end

    def ajouter
      @transaction = Transaction.new
      @transaction.compte = @compte if @compte
    end

    # def new
    # end

    def create
      if @transaction_type
        transaction_class = Types.get_class @transaction_type
        @transaction = transaction_class.new @parameters
      else
        @transaction = Comptes::Transaction.new
        @transaction.errors.add :type, "Type de transaction inconnu"
      end

      if @transaction.errors.empty? && @transaction.save
        # set the categories (workaround)
        @transaction.categories = @categories
        flash[:error] = "Erreur dans l'assignation des catégories." unless @transaction.save

        respond_to do |format|
          format.html { redirect_to @transaction }
          format.json do
            render json: { transaction: {
              id: @transaction.id,
              titre: @transaction.titre,
              somme: @transaction.somme_formattee,
              compte: @transaction.compte.nom,
              jour: @transaction.jour_formatte,
              type: @transaction.class.type_name,
              categories: @transaction.categories.collect{ |categorie| categorie.nom }.join(', ')
            }}
          end
          format.js {}
        end
      else
        respond_to do |format|
          format.html { render "new" }
          format.json { render json: { errors: @transaction.errors.messages } }
          format.js {}
        end
      end
    end

    def edit
    end

    def show
    end

    def update
      if @transaction
        @transaction.categories = @categories
      end

      if @transaction && @transaction.update(@parameters)
        respond_to do |format|
          format.html { render :show }
        end
      else
        respond_to do |format|
          format.html { render :edit }
        end
      end
    end

    def destroy
      @transaction = Comptes::Transaction.find_by_id(params[:id])
      @success = false
      if @transaction
        if @transaction.destroy
          flash[:notice] = "Transaction supprimée avec succés"
          @success = true
        else
          flash[:error] = "Impossible de supprimer la transaction"
        end
      else
        flash[:error] = "Transaction invalide. Aucune suppression."
      end

      respond_to do |format|
        format.html { redirect_to comptes_transactions_path }
        format.js {}
      end
    end

    private
      def get_transaction
        @transaction = Transaction.find_by_id params[:id]
      end

      def get_context
        @compte = Compte.find_by_id params[:compte_id]
      end

      def transaction_params
        params.require(:comptes_transaction).permit(:titre, :somme, :jour, :compte_id, :type, :negative, { categories: [] })
      end

      # Formate les parametres de la transaction
      # * convertit la somme en centimes
      def format_params parameters
        somme = parameters[:somme]
        negative_sign = parameters.delete(:negative).to_i || 0
        if ApplicationHelper::is_a_number? somme
          parameters[:somme] = ComptesHelper.encode_amount(somme) * (negative_sign == 1 ? -1 : 1)
        end

        transaction_type = get_transaction_type(parameters.delete(:type))
        categories = get_categories(parameters.delete(:categories))

        return parameters, transaction_type, categories
      end

      def get_formatted_parameters
        @parameters, @transaction_type, @categories = format_params(transaction_params)
      end

      def get_categories category_ids
        category_ids ||= []

        category_ids.collect{ |id| Category.find_by_id id }.delete_if(&:nil?)
      end

      def get_transaction_type type
        transaction_type = type ? type.to_i : nil
        Types.is_valid?(transaction_type) ? Types.value_of(transaction_type) : nil
      end

      def get_allowed_resources
        @categories = Category.order(nom: :asc)
        @comptes = Compte.order(nom: :asc)
        @types = Comptes::TransactionsController::Types
      end
  end

end

app/helpers/comptes/categories_helper.rb
module Comptes::CategoriesHelper
end

app/helpers/comptes/comptes_helper.rb
module Comptes::ComptesHelper

  # Formats a value in cents into a decimal value with 2 decimals and a final €
  def self.format_amount value, with_currency = true
    (with_currency ? "%.2f €" : "%.2f") % [ value.to_f ]
  end

  # Convertit une somme pour un stockage sous forme d'entier en centimes
  # Params:
  #   value: la somme
  # Returns:
  #   la valeur entière correspondante
  def self.encode_amount value
    (value.to_f * 100).round.to_i
  end

  # Convertit une somme stockéé en entier sous sa forme originale
  # Params:
  #   value: la somme stockée
  # Returns:
  #   la valeur correspondante
  def self.decode_amount value
    (value.to_f / 100)
  end
end

app/helpers/comptes/transactions_helper.rb
module Comptes::TransactionsHelper
end

app/views/comptes/comptes/_compte.html.erb
<div class="compte col-md-3 col-sm-6 col-xs-12">
	<div class="inner">
		<a href="<%= comptes_compte_path(compte) %>">
			<div class="solde pull-right">
				<%= compte.solde_formatte %>
			</div>
			<p>
				<%= compte.nom %>
			</p>
		</a>
	  <div class="footer">
	  	<%= link_to raw('<i class="glyphicon glyphicon-pencil"></i>'), edit_comptes_compte_path(compte) %>
	  </div>
	</div>
</div>

app/views/comptes/comptes/_form.html.erb
<%= form_for @compte, html: {class: "form-horizontal"} do |form| %>
  <%= render "shared/form_errors", model: @compte %>

  <div class="form-group">
    <%= form.label :nom, class: "col-md-3 control-label" %>
    <div class="col-md-9">
      <%= form.text_field :nom, class: "form-control", required: "", placeholder: "Nom du compte" %>
    </div>
  </div>
  <div class="form-group">
    <%= form.label :solde_historique, "Solde courant", class: "col-md-3 control-label" %>
    <div class="col-md-9">
      <% if @compte.id %>
        <!-- compte existant -->
        <%= form.number_field :solde_historique, value: @compte.solde, class: "form-control", step: 0.01, required: "", placeholder: "Montant actuel", readonly: true %>
      <% else %>
        <%= form.number_field :solde_historique, class: "form-control", step: 0.01, required: "", placeholder: "Montant actuel" %>
      <% end %>
    </div>
  </div>

  <div class="col-md-9 col-md-offset-3">
    <%= form.submit "#{@compte.id ? "Éditer" : "Créer"} le compte", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/comptes/comptes/_section_menu.html.erb
<li>
	<span class="section-title"><%= HtmlHelper::Bootstrap::glyphicon('tasks') %> Comptes</span>
	<ul>
		<li><%= link_to "Liste", comptes_comptes_path %></li>
		<li><%= link_to "Creer un compte", new_comptes_compte_path %></li>
	</ul>
</li>

<% if @compte %>
<li>
	<span class="section-title"><%= HtmlHelper::Bootstrap::glyphicon('tasks') %> [ <%= @compte.nom %> ]</span>
	<ul>
	  <li><%= link_to "Détails", comptes_compte_path(@compte) %></li>
	  <li><%= link_to "Résumé", summary_comptes_compte_path(@compte) %></li>
	  <li><%= link_to "Solde interactif", solde_comptes_compte_path(@compte) %></li>
	  <li><%= link_to "Transactions", comptes_compte_transactions_path(@compte) %></li>
	  <li><%= link_to "Statistiques", statistics_comptes_compte_path(@compte) %></li>
	  <li><%= link_to "Nouvelles transaction", ajouter_comptes_compte_transactions_path(@compte) %></li>
	  <li><%= link_to "Validation", validate_comptes_compte_path(@compte) %></li>
	</ul>
</li>
<% end %>

app/views/comptes/comptes/_solde.html.erb
<li>
	<% if @compte.validated_date %>
		<% if @date > @compte.validated_date %>
			<%= link_to validate_comptes_compte_path(@compte, date: @date),  method: :post, class: "btn btn-primary validate-solde" do %>
				<%= HtmlHelper::Bootstrap::glyphicon :ok %>
			<% end %>
		<% elsif @date == @compte.validated_date %>
			<span class="text-success"><%= HtmlHelper::Bootstrap::glyphicon :ok %></span>
		<% end %>
	<% end %>

	Au <%= @date.strftime "%d/%m/%Y" %>: <span class="badge"><%= @solde %></span>
</li>

app/views/comptes/comptes/edit.html.erb
<% if @compte %>
<% provide :title, raw("Édition du compte <strong>#{ @compte.nom }</strong>" %>

<%= render "form" %>

<% else %>

<p>Le compte <%= params[:id] %> n'existe pas.</p>

<% end %>

<div clas="row">
  <p class="col-md-12"><%= link_to "Retour à la liste", comptes_comptes_path %></p>
</div>

app/views/comptes/comptes/index.html.erb
<h1>Liste des comptes</h1>

<% if @comptes && @comptes.size > 0 %>

<div class="row flex-row">
	<%= render @comptes %>
</div>

<% else %>

<p>
  Aucun compte existant.
</p>

<% end %>

app/views/comptes/comptes/new.html.erb
<h1>Creation d'un compte</h1>

<%= render "form" %>

<p>
  <%= link_to "Retour à la liste", comptes_comptes_path %>
</p>

app/views/comptes/comptes/show.html.erb
<% if @compte %>

<% content_for :title do %>
	Compte : <%= @compte.nom %> <small><%= link_to raw('<i class="glyphicon glyphicon-pencil"></i>'), edit_comptes_compte_path(@compte) %></small>
<% end %>

<p class="lead">
  Solde : <span class="label label-info"><%= @compte.solde_formatte %></span>
</p>

<h2>Les dernières transactions</h2>
<%= render partial: 'comptes/transactions/transactions', object: @transactions %>

<h2>Outils</h2>
<div>
	<div class="btn btn-default">
		<%= link_to "Transactions en CSV", comptes_compte_transactions_path(@compte, format: 'csv') %>
	</div>
	<div class="btn btn-default">
		<%= link_to "Transactions pour Excel", comptes_compte_transactions_path(@compte, format: 'xls') %>
	</div>
</div>

<% else %>
<p class="alert alert-danger">
  Ce compte (<%= params[:id] %>) n'existe pas.
</p>
<% end %>

app/views/comptes/comptes/solde.html.erb
<% provide :page_title, "Comptes - Solde interactif" %>
<% provide :title, "Solde interactif" %>

<% if @compte %>

	<%= form_for @compte, url: { action: :solde }, method: :post, remote: true, html: { class: "form-inline row", role: "form" } do |f| %>
	  <div class="form-group col-md-8 col-md-offset-2">
	    <div class="input-group">
      	<div class="input-group-addon">
					<%= label_tag :date, "Date" %>
				</div>

				<%= date_field_tag :date, "", class: "form-control", max: Date.today, required: true, value: Date.today %>

	     	<div class="input-group-btn">
					<%= submit_tag "Voir le solde", class: "btn" %>
				</div>
	    </div>
	  </div>
	<% end %>

	<ul id="solde-values">
		<%= render "solde", date: @date, solde: @solde if @date %>
	</ul>

<% else %>

	<p>Le compte <%= params[:id] %> n'existe pas</p>

<% end %>

app/views/comptes/comptes/solde.js.erb
(function() {
	<% if @date %>

		$("<%= escape_javascript render 'solde', date: @date, solde: @solde, compte: @compte %>").appendTo("#solde-values");

	<% else %>

		var alert = $("<p>");
		alert.addClass("alert alert-danger alert-dismissible");
		alert.html('<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>[<%= DateTime.now.strftime "%Hh%M:%S" %>] Impossible de calculer le solde');

		alert.prependTo('form');

	<% end %>
})();

app/views/comptes/comptes/statistics.html.erb
<% if @compte %>
<% provide :title, "Statistiques du compte" %>

<div id="month-calendar" class="row col-sm-offset-1 col-sm-10">
	<% now = Date.today %>
	<% eldest_transaction = Comptes::Transaction.order(jour: :asc).first.jour %>
	<% eldest_month = Date.new eldest_transaction.year, eldest_transaction.month %>
	<% (now.year - 1..now.year).each do |year| %>
		<div class="row">
			<div class="col-xs-12 year">Année <%= year %></div>
		</div>
		<div class="row">
		<% (1..12).each do |month| %>
			<% date = Date.new year, month %>
			<div class="col-xs-1 btn btn-default month <%= 'disabled' if date > now || date < eldest_month %>" data-month="<%= date.strftime("%Y-%m") %>" data-account="<%= @compte.id %>">
				<%= date.strftime "%b" %>
			</div>
		<% end %>
		</div>
	<% end %>
</div>

<div class="row">
	<div class="col-md-6">
		<svg id="expenses-graphs" class="statistic-chart"></svg>
	</div>
	<div class="col-md-6">
		<svg id="revenues-graphs" class="statistic-chart"></svg>
	</div>
</div>

<% else %>

<p>Le compte <%= params[:id] %> n'existe pas.</p>

<% end %>

app/views/comptes/comptes/summary.html.erb
<% provide :title, "Évolution de la situation" %>

<!-- Mois en cours -->
<div>
	Compte <b><%= @compte.nom %></b> : <%= Comptes::ComptesHelper.format_amount @compte.solde %>
</div>

<!-- Depuis le début de l'année -->
<table id="evolution-table" class="table table-responsive">
	<thead>
		<tr>
			<th>Mois</th>
			<th>Solde en fin de mois</th>
			<th>Total</th>
			<th>Crédit</th>
			<th>Débit</th>
		</tr>
	</thead>
	<tbody>
		<% @previous_months.each do |month| %>
		<tr class="previous-month">
			<td><%= month[:date].strftime("%B %Y") %></td>
			<td><%= Comptes::ComptesHelper.format_amount month[:solde] %></td>
			<td><%= HtmlHelper::Bootstrap::value_badge(month[:expense], Comptes::ComptesHelper.format_amount(month[:expense])) %></td>
			<td><%= Comptes::ComptesHelper.format_amount month[:credit] %></td>
			<td><%= Comptes::ComptesHelper.format_amount month[:debit] %></td>
		</tr>
		<% end %>
	</tbody>
</table>

<!-- Années précédentes -->

app/views/comptes/comptes/validate.html.erb
<% if @compte %>

<% content_for :title do %>
	Diff : <%= @compte.nom %>
<% end %>

<%
	if @compte.validation_date
  	validated_solde = Comptes::ComptesHelper::decode_amount @compte.validation_solde
  	diff = @compte.solde - validated_solde
%>
<p>
  Solde validé au <b><%= @compte.validated_date.strftime "%d/%m/%Y à %Hh%M" %></b>:
  <span class="label label-info"><%= Comptes::ComptesHelper::format_amount validated_solde %></span><br/>
  Validé le <b><%= @compte.validation_date.strftime "%d/%m/%Y à %Hh%M" %></b>
</p>
<% end %>

<% unless @unvalidated_transactions.empty? %>
<p>
	Solde actuel : <span class="label label-info"><%= @compte.solde_formatte %></span>
	<%= HtmlHelper::Bootstrap::value_badge diff, Comptes::ComptesHelper::format_amount(diff) if diff %>
	<%= link_to raw(%{<i class="glyphicon glyphicon-ok"></i>}), validate_comptes_compte_path(@compte), method: :post, class: "btn btn-success validate-solde" %>
</p>
<% end %>

<h2>Transactions depuis la validation</h2>
<% unless @unvalidated_transactions.empty? %>
	<%= will_paginate @unvalidated_transactions %>
	<%= render partial: 'comptes/transactions/transactions', object: @unvalidated_transactions %>
	<%= will_paginate @unvalidated_transactions %>
<% else %>
	<p>Aucune transaction depuis la dernière validation.</p>
<% end %>

<% else %>
<p class="alert alert-danger">
  Ce compte (<%= params[:id] %>) n'existe pas.
</p>
<% end %>