config/routes.rb
Myhome::Application.routes.draw do
  root 'home#welcome'

  namespace :comptes do
    get "/" => "transactions#index"

    concern :with_transactions do |options|
      resources :transactions, options do
        collection do
          get "ajouter"
        end
      end
    end

    concerns :with_transactions
    resources :transaction_monnaies, controller: "transactions"
    resources :transaction_cartes, controller: "transactions"
    resources :transfers, controller: "transactions"

    resources :comptes, concerns: [ :with_transactions ] do
      member do
        get :solde
        post :solde
        get :summary
        get :statistics
        post :statistics
        get :validate
        post :validate
      end
    end

    resources :categories
  end

  namespace :date_marker do
    resources :events do
      member do
        get :get_day
        post :get_day
      end
    end
  end

end

app/models/date_marker.rb
module DateMarker
  def self.table_name_prefix
    'date_marker_'
  end
end

app/models/date_marker/event.rb
class DateMarker::Event < ActiveRecord::Base
  validates :title, presence: true
  validates :day, presence: true

  def number_of_days
    (Date.today - day).to_i
  end

  def number_of_months
    today = Date.today
    (today.year * 12 + today.month) - (day.year * 12 + day.month)
  end

  def number_of_years
    (number_of_months / 12).to_i
  end
end

app/controllers/date_marker/events_controller.rb
module DateMarker

  class EventsController < ApplicationController
    before_action :get_event, on: [:show, :edit, :update, :get_day]

    def index
      @events = Event.all
    end

    def show
    end

    def new
      @event = Event.new
    end

    def create
      @event = Event.new event_params
      # @event.day = Date::parse

      if @event.save
        redirect_to @event
      else
        render 'new'
      end
    end

    def edit
    end

    def update
      unless @event
        render :edit
      end

      if @event.update event_params
        redirect_to @event
      else
        render :edit
      end
    end

    def get_day
      @dates = {}
      return unless @event

      if request.post?
        time_span = params[:time_span] ? params[:time_span].to_sym : nil

        unless ApplicationHelper::is_a_number? params[:number]
          flash.now[:error] = "'#{params[:number]}' is not a number"
          return
        end
        number = params[:number].to_i

        case time_span
        when :days
          @dates["#{number} jours"] = @event.day + number
        when :months
          @dates["#{number} mois"] = @event.day >> number
        else
          flash.now[:error] = "'#{params[:time_span]}' is an invalid time span"
        end
      end
    end

    private
      def event_params
        params.require(:date_marker_event).permit(:title, :day)
      end

      def get_event
        @event = Event.find_by_id params[:id]
      end
  end

end

app/helpers/date_marker/events_helper.rb
module DateMarker::EventsHelper
end

app/views/date_marker/events/_form.html.erb
<%= form_for @event, html: { class: 'form-horizontal', role: "form" } do |form| %>
  <%= render "shared/form_errors", model: @event %>

  <div class='form-group'>
    <%= form.label :title, class: "col-md-3 control-label" %>
    <div class="col-md-9">
      <%= form.text_field :title, required: true, placeholder: "Nom de l'événement", class: "form-control" %>
    </div>
  </div>

  <div class='form-group'>
    <%= form.label :day, class: "col-md-3 control-label" %>
    <div class="col-md-9">
      <%= form.date_field :day, required: true, placeholder: "aaaa-mm-jj" %>
    </div>
  </div>

  <div class='form-group'>
    <div class="col-md-offset-3 col-md-9">
      <%= form.submit "Créer", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/date_marker/events/_get_day_date.html.erb
		<li><%= target %> le <%= ApplicationHelper::format_date date %></li>

app/views/date_marker/events/_section_menu.html.erb
<!-- Section menu -->
<li>
	<span class="section-title"><%= HtmlHelper::Bootstrap::glyphicon('tasks') %> Date Marks</span>
	<ul>
	  <li><%= link_to "Liste", date_marker_events_path %></li>
	  <li><%= link_to "Nouvel évenement", new_date_marker_event_path %></li>
	</ul>
</li>

app/views/date_marker/events/edit.html.erb
<% if @event %>

<h1>Edition de l'événement</h1>

<%= render 'form' %>

<p>
  <%= link_to "Retour à l'événement", @event %>
</p>

<% else %>

<p>
  L'événement <%= params[:id] %> n'existe pas.
</p>

<p>
  <%= link_to "Retour à la liste d'événements", date_marker_events_path %>
</p>

<% end %>

app/views/date_marker/events/get_day.html.erb
<% if @event %>

<h1><em><%= @event.title %></em> (le <%= ApplicationHelper::format_date @event.day %>)</h1>

<h2>Situation actuelle</h2>
<p>
	<%= @event.number_of_days %> jours ~ <%= @event.number_of_months %> mois depuis l'événement.
</p>

<h2>Dates à retenir</h2>
<%= form_for @event, url: { action: :get_day }, method: :post, remote: true, html: { id: 'get-day-form', class: "form-inline row", role: "form" } do |f| %>
	  <div class="form-group">
			<%= number_field_tag :number, "", class: "form-control", required: true, min: 0, step: 1, placeholder: "Nombre" %>
			<%= select_tag :time_span, options_for_select([%W{jours days}, %W{mois months}]), class: "form-control", required: true %>
	    <div class="input-group">
	     	<div class="input-group-btn">
					<%= submit_tag "Trouver la date", class: "btn btn-primary" %>
				</div>
	    </div>
	  </div>
<% end %>

<ul id="date-list">
	<% @dates.each do |target, date| %>
		<%= render "get_day_date", target: target, date: date %>
	<% end %>
</ul>

<% else %>

<p>Aucun event à l'id <%= params[:id] %>.</p>

<% end %>

app/views/date_marker/events/get_day.js.erb
$("#get-day-errors").empty();

<% unless @dates.empty? %>

	<% @dates.each do |target, date| %>
	  $("<%= escape_javascript render %Q{get_day_date}, target: target, date: date %>").prependTo("#date-list");
	<% end %>

<% else %>

	<%
	# Wrap errors to use partials
	error_model = class << Object.new
		def any?
			true
		end

		def errors
			self
		end

		def full_messages
			[ %Q{Error in the form} ]
		end
	end
	%>

  $('form').prepend("<%= escape_javascript render 'shared/form_errors', model: error_model, wrapper_id: 'get-day-errors' %>");

<% end %>

app/views/date_marker/events/index.html.erb
<h1>Liste de événements</h1>

<% unless @events.empty? %>

<div id='event-list'>
  <% @events.each_with_index do |event, index| %>
  <div class='row event'>
    <h2 class="col-md-12"><%= link_to event.title, event %></h2>

    <p class='col-md-6'>
      <strong class='label label-info'><%= pluralize(event.number_of_days , "jour") %></strong> depuis l'évenement
    </p>

    <p class='col-md-6'>
      <strong class='label label-info'><%= pluralize(event.number_of_months , "mois") %></strong> depuis l'évenement
    </p>
  </div>
  <% end %>
</div>

<% else %>

  <p>Aucun événement pour le moment</p>

<% end %>

<p>
  <%= link_to "Ajouter un nouvel événement", new_date_marker_event_path %>
</p>

app/views/date_marker/events/new.html.erb
<h1>Ajouter un nouvel événement</h1>

<%= render 'form' %>

<p>
  <%= link_to "Retour à la liste d'événements", date_marker_events_path %>
</p>

app/views/date_marker/events/show.html.erb
<% if @event %>

<h1><%= @event.title %> : <%= @event.day.strftime("%m/%d/%Y") %></h1>

<p>
    Nombre de mois depuis l'événement : <strong class='label label-info'><%= pluralize(@event.number_of_days , "jour") %></strong>
</p>

<p>
    Nombre de mois depuis l'événement : <strong class='label label-info'><%= pluralize(@event.number_of_months , "mois") %></strong>
</p>

<p>
  <%= link_to raw('Éditer <i class="glyphicon glyphicon-pencil"></i>'), edit_date_marker_event_path(@event) %>
</p>

<% else %>

<p>
  Aucun événement existant pour l'id <%= params[:id] %>
</p>

<% end %>

<p>
  <%= link_to "Retour à la liste", date_marker_events_path %>
</p>